DROP TABLE IF EXISTS "task" CASCADE;
DROP TABLE IF EXISTS "ticket" CASCADE;
DROP TABLE IF EXISTS "cliente" CASCADE;
DROP TABLE IF EXISTS "escopo" CASCADE;
DROP TABLE IF EXISTS "produto" CASCADE;
DROP TABLE IF EXISTS "type_task" CASCADE;
DROP TABLE IF EXISTS "status_task" CASCADE;
